import { Router } from "express";
import authRoutes from "./auth.routes";
import categoryRoutes from "./category.routes";
import productRoutes from "./product.routes";
import variantRoutes from "./variant.routes";
import pointRoutes from "./point.routes";
import inventoryRoutes from "./inventory.routes";
import orderRoutes from "./order.routes";
import cashflowRoutes from "./cashflow.routes";
import voucherRoutes from "./voucher.routes";
import addressRoutes from "./address.routes";
import uploadRoutes from "./upload.routes";
import wishlistRoutes from "./wishlist.routes";
import reviewRoutes from "./review.routes";
import supplierRoutes from "./supplier.routes";
import purchaseOrderRoutes from "./purchaseOrder.routes";
import notificationRoutes from "./notification.routes";
import userRoutes from "./user.routes";
import stockTransferRoutes from "./stockTransfer.routes";
import restockRequestRoutes from "./restockRequest.routes";
import deliveryAreaRoutes from "./deliveryArea.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/stock-transfers", stockTransferRoutes);
router.use("/restock-requests", restockRequestRoutes);
router.use("/delivery-areas", deliveryAreaRoutes);
router.use("/categories", categoryRoutes);
router.use("/products", productRoutes);
router.use("/variants", variantRoutes);
router.use("/points", pointRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/orders", orderRoutes);
router.use("/cashflow", cashflowRoutes);
router.use("/vouchers", voucherRoutes);
router.use("/addresses", addressRoutes);
router.use("/upload", uploadRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/reviews", reviewRoutes);
router.use("/suppliers", supplierRoutes);
router.use("/purchase-orders", purchaseOrderRoutes);
router.use("/notifications", notificationRoutes);

export default router;
